packages:
    - 'libs/*'
    - 'consumers/*'

allowBuilds:
    '@confluentinc/kafka-javascript': true
    '@google/genai': true
    '@parcel/watcher': false
    esbuild: true
    msgpackr-extract: true
    protobufjs: true
    unrs-resolver: true

overrides:
    equipped: 5.3.0
    valleyed: 4.5.22

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
    - equipped@5.3.0
