packages:
    - 'libs/*'
    - 'consumers/*'

allowBuilds:
    '@confluentinc/kafka-javascript': true
    '@parcel/watcher': false
    esbuild: true
    msgpackr-extract: true
    protobufjs: true
    unrs-resolver: true

overrides:
    equipped: file://~/Desktop/code/packages/equipped
    valleyed: 4.5.23

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
    - equipped
    - valleyed
